/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManagerRole;

import Business.Airliner;
import Business.AirlinerSchedule;
import Interface.UserInformation.ManageCustomerJPanel;
import Business.TravelAgent;
import Interface.ManagerRole.AirLinerRole.ManageAirlinerCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author aviti
 */
public class AgentWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel RightJPanel;
    private TravelAgent travelagent;
    private AirlinerSchedule airlinerschedule;
   
    public AgentWorkAreaJPanel(JPanel RightJPanel, TravelAgent travelagent,AirlinerSchedule airlinerschedule) {
        
         initComponents();
        
        this.RightJPanel=RightJPanel;
        this.travelagent=travelagent;
        this.airlinerschedule=airlinerschedule;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ManageAirlinerBTN = new javax.swing.JButton();
        ManageCustomerBtn = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Manage Travel Agent Work Area");

        ManageAirlinerBTN.setText("Manage Airliner");
        ManageAirlinerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAirlinerBTNActionPerformed(evt);
            }
        });

        ManageCustomerBtn.setText("Manage Customer");
        ManageCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCustomerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ManageAirlinerBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ManageAirlinerBTN)
                .addGap(60, 60, 60)
                .addComponent(ManageCustomerBtn)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void ManageAirlinerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAirlinerBTNActionPerformed
        // TODO add your handling code here:
        
        
        ManageAirlinersJPanel manageAirliners = new ManageAirlinersJPanel(RightJPanel,travelagent,airlinerschedule);
        RightJPanel.add("ManageAirlinersJPanel",manageAirliners);
        CardLayout layout =(CardLayout)RightJPanel.getLayout();
        layout.next(RightJPanel);
        
    }//GEN-LAST:event_ManageAirlinerBTNActionPerformed

    private void ManageCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCustomerBtnActionPerformed
        // TODO add your handling code here:
        
        
       
        
      CustomerBookingJPanel cust = new CustomerBookingJPanel(RightJPanel,airlinerschedule,travelagent);
        RightJPanel.add("CustomerBookingJPanel",cust);
        CardLayout layout =(CardLayout)RightJPanel.getLayout();
        layout.next(RightJPanel);
        
    }//GEN-LAST:event_ManageCustomerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageAirlinerBTN;
    private javax.swing.JButton ManageCustomerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
