/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManagerRole;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.AirlinerSchedule;
import Business.TravelAgent;
import Interface.ManagerRole.AirLinerRole.ViewAirlinerScheduleJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aviti
 */
public class ManageAirlinersJPanel extends javax.swing.JPanel {
private JPanel RightJPanel;
private TravelAgent travelagent;
private Airliner airliner;
private AirlinerSchedule airlinerschedule;
    /**
     * Creates new form ManageAirliners
     */
   

   public ManageAirlinersJPanel(JPanel RightJPanel, TravelAgent travelagent, AirlinerSchedule airlinerSchedule) {
        initComponents();
        this.RightJPanel=RightJPanel;
        this.travelagent=travelagent;
        this.airliner=airliner;
        this.airlinerschedule=airlinerSchedule;
        populate();
        
        
        
   }
 public void populate(){
        DefaultTableModel dtm = (DefaultTableModel)AirlinerTable.getModel();
        dtm.setRowCount(0);
        
        for(Airliner a : travelagent.getAirlinerDirectory().getAirlinerDirect()){
            Object[] row = new Object[3];
            row[0]=a;
            row[1]=a.getAirlinerID();
            row[2]=a.getAirlinerPhonenumber();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AirlinerTable = new javax.swing.JTable();
        NewAirlinerBtn = new javax.swing.JButton();
        ViewAirlinerBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(640, 501));
        setLayout(new java.awt.CardLayout());

        AirlinerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Airliner ID", "Airliner PhoneNumber"
            }
        ));
        jScrollPane1.setViewportView(AirlinerTable);

        NewAirlinerBtn.setText("New Airliner>>");
        NewAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAirlinerBtnActionPerformed(evt);
            }
        });

        ViewAirlinerBtn.setText("View Airliner>>");
        ViewAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAirlinerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(363, 363, 363)
                                .addComponent(NewAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(449, Short.MAX_VALUE)
                        .addComponent(ViewAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(NewAirlinerBtn)
                .addGap(34, 34, 34)
                .addComponent(ViewAirlinerBtn)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void ViewAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAirlinerBtnActionPerformed
        // TODO add your handling code here:
        int selectRow=AirlinerTable.getSelectedRow();
        if(selectRow<0){
        JOptionPane.showMessageDialog(null, "Please Select a Row");
        
        
        
        }else{
        
        Airliner airline=(Airliner) AirlinerTable.getValueAt(selectRow, 0);
        ViewAirlinersJPanel vPanel= new  ViewAirlinersJPanel(RightJPanel,airline,travelagent);
        RightJPanel.add("ViewPanel",vPanel);
        CardLayout layout =(CardLayout)RightJPanel.getLayout();
        layout.next(RightJPanel);
        
        
        
        
        
    }//GEN-LAST:event_ViewAirlinerBtnActionPerformed
    }
    private void NewAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAirlinerBtnActionPerformed
        // TODO add your handling code here:
    
        
         
        AddAirlinersJPanel addAirliners = new AddAirlinersJPanel(RightJPanel,travelagent,airlinerschedule);
        RightJPanel.add("AddAirlinerJPanel",addAirliners);
        CardLayout layout =(CardLayout)RightJPanel.getLayout();
        layout.next(RightJPanel);   
        
        
    }//GEN-LAST:event_NewAirlinerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AirlinerTable;
    private javax.swing.JButton NewAirlinerBtn;
    private javax.swing.JButton ViewAirlinerBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
