/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.AirlinerSchedule;
import Interface.ManagerRole.AgentWorkAreaJPanel;
import Interface.ManagerRole.ManageAirlinersJPanel;
import java.awt.CardLayout;
import  Business.TravelAgent;
import Interface.ManagerRole.AirLinerRole.AirlinerManagementJPanel;
import Interface.UserInformation.ManageCustomerJPanel;

/**
 *
 * @author aviti
 */
public class MainJFrame extends javax.swing.JFrame {
private TravelAgent travelAgent;

private AirlinerSchedule airlinerschedule;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        travelAgent =new TravelAgent();
        airlinerschedule = new AirlinerSchedule ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        LeftJPanel = new javax.swing.JPanel();
        TravelAgentBtn = new javax.swing.JButton();
        AirlinersBtn = new javax.swing.JButton();
        RightJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        TravelAgentBtn.setText("Travel Agent");
        TravelAgentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TravelAgentBtnActionPerformed(evt);
            }
        });

        AirlinersBtn.setText("Airliners");
        AirlinersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlinersBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftJPanelLayout = new javax.swing.GroupLayout(LeftJPanel);
        LeftJPanel.setLayout(LeftJPanelLayout);
        LeftJPanelLayout.setHorizontalGroup(
            LeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TravelAgentBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(AirlinersBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LeftJPanelLayout.setVerticalGroup(
            LeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftJPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(TravelAgentBtn)
                .addGap(66, 66, 66)
                .addComponent(AirlinersBtn)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(LeftJPanel);

        RightJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(RightJPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TravelAgentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TravelAgentBtnActionPerformed
        // TODO add your handling code here:
        
        AgentWorkAreaJPanel agent = new AgentWorkAreaJPanel(RightJPanel, travelAgent,airlinerschedule);
        RightJPanel.add("AgentWorkAreaJPanel",agent);
        CardLayout layout =(CardLayout)RightJPanel.getLayout();
        layout.next(RightJPanel);
        
    }//GEN-LAST:event_TravelAgentBtnActionPerformed

    private void AirlinersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlinersBtnActionPerformed
        // TODO add your handling code here:
        
        AirlinerManagementJPanel airlinermanager = new AirlinerManagementJPanel(RightJPanel, airlinerschedule,travelAgent);
        RightJPanel.add("AirlinerManagementJPanel",airlinermanager);
        CardLayout layout =(CardLayout)RightJPanel.getLayout();
        layout.next(RightJPanel);
        
    }//GEN-LAST:event_AirlinersBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AirlinersBtn;
    private javax.swing.JPanel LeftJPanel;
    private javax.swing.JPanel RightJPanel;
    private javax.swing.JButton TravelAgentBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
