/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManagerRole.AirLinerRole;

import Business.Airliner;
import Business.AirlinerSchedule;
import Business.TravelAgent;
import Interface.ManagerRole.ManageAirlinersJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author aviti
 */


public class AirlinerManagementJPanel extends javax.swing.JPanel {
private JPanel RightJPanel;
private TravelAgent travelAgent;
private AirlinerSchedule airlineschedule;
    /**
     * Creates new form AirlinerManagementJPanel
     */
  
    public AirlinerManagementJPanel(JPanel RightJPanel, AirlinerSchedule airlineschedule,TravelAgent travelAgent) {
       initComponents();
       
       this.RightJPanel=RightJPanel;
       this.travelAgent=travelAgent;
       this.airlineschedule=airlineschedule;
       
      AirlinerDropdown.removeAllItems();
       for(Airliner a : travelAgent.getAirlinerDirectory().getAirlinerDirect()) {
           AirlinerDropdown.addItem(a);
    }
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ManageScheduleBtn = new javax.swing.JButton();
        AirlinerDropdown = new javax.swing.JComboBox();

        setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Airline Management Work Area");

        ManageScheduleBtn.setText("Manage Schedule");
        ManageScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageScheduleBtnActionPerformed(evt);
            }
        });

        AirlinerDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AirlinerDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlinerDropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AirlinerDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManageScheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(AirlinerDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ManageScheduleBtn)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void ManageScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageScheduleBtnActionPerformed
        // TODO add your handling code here:
        
        ManageAirlinerCatalog manageCatalog = new ManageAirlinerCatalog(RightJPanel,airlineschedule,travelAgent);
        RightJPanel.add("ManageAirlinersCatalog",manageCatalog);
        CardLayout layout =(CardLayout)RightJPanel.getLayout();
        layout.next(RightJPanel);
        
        
    }//GEN-LAST:event_ManageScheduleBtnActionPerformed

    private void AirlinerDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlinerDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirlinerDropdownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AirlinerDropdown;
    private javax.swing.JButton ManageScheduleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
