/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManagerRole.AirLinerRole;

import Business.Airliner;
import Business.TravelAgent;
import javax.swing.JPanel;
import Business.AirlinerSchedule;
import Business.AirlinerScheduleDirectory;
import Interface.ManagerRole.ManageAirlinersJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import static java.util.Collections.list;
import java.util.Locale;
import javax.swing.JOptionPane;
        
/**
 *
 * @author aviti
 */

public class CreateAirlinerJPanel extends javax.swing.JPanel {

   private JPanel RightJPanel;
   
   private AirlinerSchedule airlinerschedule;
   private TravelAgent travelagent;

    CreateAirlinerJPanel(JPanel RightJPanel,    TravelAgent travelagent, AirlinerSchedule airlinerschedule) {
        initComponents();
        this.RightJPanel=RightJPanel;
        this.travelagent=travelagent;
        
        this.airlinerschedule=airlinerschedule;
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AirlinerNameLabel = new javax.swing.JLabel();
        AirlinerIdLabel = new javax.swing.JLabel();
        DepartureTextField = new javax.swing.JTextField();
        AirlinerPhoneNumberLabel = new javax.swing.JLabel();
        ArrivalTextField = new javax.swing.JTextField();
        AirlinerDescriptionLabel = new javax.swing.JLabel();
        TakeoftimeTextField = new javax.swing.JTextField();
        AddScheduleBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        AirlinerDescriptionLabel2 = new javax.swing.JLabel();
        DateTextField = new javax.swing.JTextField();
        AirlinerNameLabel1 = new javax.swing.JLabel();
        FlightNumberTextField = new javax.swing.JTextField();
        AirlineNameTextField = new javax.swing.JTextField();
        SeatSelection = new javax.swing.JLabel();
        SeatSelectionBox = new javax.swing.JComboBox();

        setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create Airliner Schedule");

        AirlinerNameLabel.setText("Airline");

        AirlinerIdLabel.setText("Departure Location");

        AirlinerPhoneNumberLabel.setText("Arrival Location");

        AirlinerDescriptionLabel.setText("Airline Schedule Time");

        AddScheduleBtn.setText("Add Schedule");
        AddScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddScheduleBtnActionPerformed(evt);
            }
        });

        BackBtn.setText("<<Back Button");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        AirlinerDescriptionLabel2.setText("Date (MM/DD/YYYY)");

        AirlinerNameLabel1.setText("Flight Number");

        AirlineNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlineNameTextFieldActionPerformed(evt);
            }
        });

        SeatSelection.setText("Seat ");

        SeatSelectionBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(BackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddScheduleBtn)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(133, 205, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(178, 178, 178))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AirlinerDescriptionLabel2)
                    .addComponent(AirlinerDescriptionLabel)
                    .addComponent(AirlinerPhoneNumberLabel)
                    .addComponent(AirlinerIdLabel)
                    .addComponent(AirlinerNameLabel1)
                    .addComponent(AirlinerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeatSelection))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ArrivalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TakeoftimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(AirlineNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FlightNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DepartureTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addComponent(SeatSelectionBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlinerNameLabel)
                    .addComponent(AirlineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlinerNameLabel1)
                    .addComponent(FlightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlinerIdLabel)
                    .addComponent(DepartureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AirlinerPhoneNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ArrivalTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlinerDescriptionLabel)
                    .addComponent(TakeoftimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlinerDescriptionLabel2)
                    .addComponent(DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeatSelection)
                    .addComponent(SeatSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn)
                    .addComponent(AddScheduleBtn))
                .addContainerGap())
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void AddScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddScheduleBtnActionPerformed
        // TODO add your handling code here:

     try{    
        String airline=AirlineNameTextField.getText();
        String flightnumber=FlightNumberTextField.getText();
        String departure=DepartureTextField.getText();
        String arrival =ArrivalTextField.getText();
        
        String schedule=TakeoftimeTextField.getText();
        
        String date=DateTextField.getText();
        
        
        DateFormat format = new SimpleDateFormat("MM/DD/YYYY", Locale.ENGLISH);
        
        
          java.util.Date dated = format.parse(date);
        
       
        
        
        
        
        if(airline.isEmpty()==true || flightnumber.isEmpty()==true || departure.isEmpty()==true || arrival.isEmpty()==true || schedule.isEmpty()==true ){
        throw new Exception();
        }
        else{
           
            AirlinerSchedule airlinersched =airlinerschedule.getAirlineScheduleDirectory().addAirlinersschedule();
                    
       airlinersched.setAirline(airline);
            airlinersched.setFlightNumber(flightnumber);
            airlinersched.setDepartureLocation(departure);
            airlinersched.setArrivalLocation(arrival);
            airlinersched.setTimeofDay(schedule);
            airlinersched.setDate(date);
            
            JOptionPane.showMessageDialog(null, "Airliner Added Successfully");
            
      
                   
        }
    }                                         
catch(Exception e){

e.getMessage();
JOptionPane.showMessageDialog(null, "Please enter correct values");

}

        

    }//GEN-LAST:event_AddScheduleBtnActionPerformed

     private void backAction() {
        RightJPanel.remove(this);
        Component[] componentArray = RightJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirlinerCatalog manageAirlinerCatalog = (ManageAirlinerCatalog) component;
        manageAirlinerCatalog.populate();
        CardLayout layout = (CardLayout) RightJPanel.getLayout();
        layout.previous(RightJPanel);
    }
    
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:

       backAction();
        
        
        
    }//GEN-LAST:event_BackBtnActionPerformed

    private void AirlineNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlineNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirlineNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddScheduleBtn;
    private javax.swing.JTextField AirlineNameTextField;
    private javax.swing.JLabel AirlinerDescriptionLabel;
    private javax.swing.JLabel AirlinerDescriptionLabel2;
    private javax.swing.JLabel AirlinerIdLabel;
    private javax.swing.JLabel AirlinerNameLabel;
    private javax.swing.JLabel AirlinerNameLabel1;
    private javax.swing.JLabel AirlinerPhoneNumberLabel;
    private javax.swing.JTextField ArrivalTextField;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField DateTextField;
    private javax.swing.JTextField DepartureTextField;
    private javax.swing.JTextField FlightNumberTextField;
    private javax.swing.JLabel SeatSelection;
    private javax.swing.JComboBox SeatSelectionBox;
    private javax.swing.JTextField TakeoftimeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
