/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManagerRole.AirLinerRole;

import Business.Airliner;
import Business.AirlinerSchedule;
import Business.TravelAgent;
import Interface.ManagerRole.ViewAirlinersJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aviti
 */
public class ManageAirlinerCatalog extends javax.swing.JPanel {

    private JPanel RightJPanel;
    
    private AirlinerSchedule airlinerschedule;
    
    private TravelAgent travelagent;
   
    
    /**
     * Creates new form ManageAirlinerCatalog
     */
   public  ManageAirlinerCatalog(JPanel RightJPanel, AirlinerSchedule airlinerschedule, TravelAgent travelagent) {
        initComponents();
        this.RightJPanel=RightJPanel;
        this.airlinerschedule=airlinerschedule;
        this.travelagent=travelagent;
        populate();
        
        
        
              
    }

 public void populate(){
        DefaultTableModel dtm = (DefaultTableModel)AirlinerCatalog.getModel();
        dtm.setRowCount(0);
        
        for(AirlinerSchedule B : airlinerschedule.getAirlineScheduleDirectory().getAirlinerScheduleDirect()){
            Object[] row = new Object[3];
            row[0]=B;
            row[1]=B.getAirline();
            row[2]=B.getFlightNumber();
            
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AirlinerCatalog = new javax.swing.JTable();
        DeleteScheduleBtn = new javax.swing.JButton();
        backButton4 = new javax.swing.JButton();
        createAirlinerScheduleBtn = new javax.swing.JButton();
        ViewAirlinerBtn = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jLabel1.setText("Airliner Catalog");

        AirlinerCatalog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AirlinerCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Flight Number"
            }
        ));
        jScrollPane1.setViewportView(AirlinerCatalog);

        DeleteScheduleBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DeleteScheduleBtn.setText("Delete Schedule");
        DeleteScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteScheduleBtnActionPerformed(evt);
            }
        });

        backButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });

        createAirlinerScheduleBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createAirlinerScheduleBtn.setText("Create Airliner Schedule >>");
        createAirlinerScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirlinerScheduleBtnActionPerformed(evt);
            }
        });

        ViewAirlinerBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ViewAirlinerBtn.setText("ViewAirliner Schedule>>");
        ViewAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAirlinerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteScheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createAirlinerScheduleBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ViewAirlinerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(221, 221, 221))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewAirlinerBtn)
                    .addComponent(DeleteScheduleBtn))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAirlinerScheduleBtn)
                    .addComponent(backButton4))
                .addGap(32, 32, 32))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteScheduleBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = AirlinerCatalog.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                AirlinerSchedule sched = (AirlinerSchedule)AirlinerCatalog.getValueAt(selectedRow, 0);
                airlinerschedule.getAirlineScheduleDirectory().removeAirlinerSchedule(sched);
                populate();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
        
        
        
        
    }//GEN-LAST:event_DeleteScheduleBtnActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
       
        RightJPanel.remove(this);
        
    }//GEN-LAST:event_backButton4ActionPerformed

    private void createAirlinerScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirlinerScheduleBtnActionPerformed

        CreateAirlinerJPanel create = new CreateAirlinerJPanel(RightJPanel,travelagent, airlinerschedule);
        RightJPanel.add("CreateAirlinerJPanel",create);
        CardLayout layout =(CardLayout)RightJPanel.getLayout();
        layout.next(RightJPanel);
        
        
        
       


        
        
    }//GEN-LAST:event_createAirlinerScheduleBtnActionPerformed

    private void ViewAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAirlinerBtnActionPerformed
        // TODO add your handling code here:
        
        
        int selectRow=AirlinerCatalog.getSelectedRow();
        if(selectRow<0){
        JOptionPane.showMessageDialog(null, "Please Select a Row");
        
        
        
        }else{
        
        AirlinerSchedule airlinerschedule=(AirlinerSchedule)AirlinerCatalog.getValueAt(selectRow, 0);
        ViewAirlinerScheduleJPanel vPanel= new    ViewAirlinerScheduleJPanel(RightJPanel,travelagent,airlinerschedule);
        RightJPanel.add("ViewAirlinerSchedule",vPanel);
        CardLayout layout =(CardLayout)RightJPanel.getLayout();
        layout.next(RightJPanel);
        }
    }//GEN-LAST:event_ViewAirlinerBtnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AirlinerCatalog;
    private javax.swing.JButton DeleteScheduleBtn;
    private javax.swing.JButton ViewAirlinerBtn;
    private javax.swing.JButton backButton4;
    private javax.swing.JButton createAirlinerScheduleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
