/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManagerRole.AirLinerRole;

import Business.Airliner;
import Business.AirlinerSchedule;
import Business.TravelAgent;
import Interface.ManagerRole.ManageAirlinersJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aviti
 */

public class ViewAirlinerScheduleJPanel extends javax.swing.JPanel {
private TravelAgent travelagent;
private Airliner airline;
private JPanel RightJPanel;
private AirlinerSchedule airlinerschedule;

    /**
     * Creates new form ViewAirlinerJPanel
     */
    
   
   public ViewAirlinerScheduleJPanel(JPanel RightJPanel,TravelAgent travelagent, AirlinerSchedule airlinerschedule) {
        initComponents();
        
        
        
        this.airlinerschedule=airlinerschedule;
        this.RightJPanel=RightJPanel;
        this.travelagent=travelagent;
        
        
        
        AirlineNameTextField.setText(airlinerschedule.getAirline());
        FlightNumberTextField.setText(airlinerschedule.getFlightNumber());
        DepartureTextField.setText(airlinerschedule.getDepartureLocation());
        ArrivalTextField.setText(airlinerschedule.getArrivalLocation());
        
        TakeoftimeTextField.setText(airlinerschedule.getTimeofDay());
        
        DateTextField.setText(airlinerschedule.getDate());
        
         seat.removeAllItems();
       for(AirlinerSchedule a : airlinerschedule.getAirlineScheduleDirectory().getAirlinerScheduleDirect()) {
           seat.addItem(a);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AirlinerNameLabel = new javax.swing.JLabel();
        AirlineNameTextField = new javax.swing.JTextField();
        AirlinerNameLabel1 = new javax.swing.JLabel();
        FlightNumberTextField = new javax.swing.JTextField();
        AirlinerIdLabel = new javax.swing.JLabel();
        DepartureTextField = new javax.swing.JTextField();
        AirlinerPhoneNumberLabel = new javax.swing.JLabel();
        ArrivalTextField = new javax.swing.JTextField();
        AirlinerDescriptionLabel = new javax.swing.JLabel();
        TakeoftimeTextField = new javax.swing.JTextField();
        AirlinerDescriptionLabel2 = new javax.swing.JLabel();
        DateTextField = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        seat = new javax.swing.JComboBox();

        setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("View Airliner Schedule");

        AirlinerNameLabel.setText("Airline");

        AirlinerNameLabel1.setText("Flight Number");

        AirlinerIdLabel.setText("Departure Location");

        AirlinerPhoneNumberLabel.setText("Arrival Location");

        AirlinerDescriptionLabel.setText("Airline Schedule Time");

        AirlinerDescriptionLabel2.setText("Date (MM/DD/YYYY)");

        BackBtn.setText("<<Back Button");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        seat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(BackBtn)))
                .addContainerGap(237, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AirlinerDescriptionLabel2)
                            .addComponent(AirlinerDescriptionLabel)
                            .addComponent(AirlinerPhoneNumberLabel)
                            .addComponent(AirlinerIdLabel)
                            .addComponent(AirlinerNameLabel1)
                            .addComponent(AirlinerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ArrivalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TakeoftimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AirlineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(FlightNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DepartureTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(178, 178, 178))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AirlinerNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlinerNameLabel1)
                    .addComponent(FlightNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlinerIdLabel)
                    .addComponent(DepartureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AirlinerPhoneNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ArrivalTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlinerDescriptionLabel)
                    .addComponent(TakeoftimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AirlinerDescriptionLabel2)
                    .addComponent(DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(27, 27, 27)
                .addComponent(BackBtn)
                .addContainerGap())
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:

        backAction();

    }//GEN-LAST:event_BackBtnActionPerformed

    private void backAction() {
        RightJPanel.remove(this);
        Component[] componentArray = RightJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirlinerCatalog manageairlinercat = (ManageAirlinerCatalog) component;
        manageairlinercat.populate();
        CardLayout layout = (CardLayout) RightJPanel.getLayout();
        layout.previous(RightJPanel);
    }
    
    
    
    
    
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        AirlineNameTextField.setEditable(false);
        FlightNumberTextField.setEditable(true);
        DepartureTextField.setEnabled(true);
        ArrivalTextField.setEnabled(true);
        TakeoftimeTextField.setEnabled(true);
        DateTextField.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
      AirlineNameTextField.setEditable(true);
        FlightNumberTextField.setEditable(true);
        DepartureTextField.setEnabled(true);
        ArrivalTextField.setEnabled(true);
       TakeoftimeTextField.setEnabled(true);
       DateTextField.setEnabled(true);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        try{

        String airline=AirlineNameTextField.getText();
        String flightnumber=FlightNumberTextField.getText();
        String departure=DepartureTextField.getText();
        String arrival =ArrivalTextField.getText();
        
        String schedule=TakeoftimeTextField.getText();
        
        String date=DateTextField.getText();
        DateFormat format = new SimpleDateFormat("MM/DD/YYYY", Locale.ENGLISH);
          java.util.Date dated = format.parse(date);

            if(airline.isEmpty()==true || flightnumber.isEmpty()==true || departure.isEmpty()==true || arrival.isEmpty()==true || schedule.isEmpty()==true ){
                throw new Exception();

            }
            else{
            airlinerschedule.setAirline(airline);
           airlinerschedule.setFlightNumber(flightnumber);
            airlinerschedule.setDepartureLocation(departure);
            airlinerschedule.setArrivalLocation(arrival);
            airlinerschedule.setTimeofDay(schedule);
            airlinerschedule.setDate(date);
            JOptionPane.showMessageDialog(null, "Airliner Added Successfully");
           
        }
        }

        catch(Exception e){

            e.getMessage();
            JOptionPane.showMessageDialog(null, "Please enter correct values");

        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AirlineNameTextField;
    private javax.swing.JLabel AirlinerDescriptionLabel;
    private javax.swing.JLabel AirlinerDescriptionLabel2;
    private javax.swing.JLabel AirlinerIdLabel;
    private javax.swing.JLabel AirlinerNameLabel;
    private javax.swing.JLabel AirlinerNameLabel1;
    private javax.swing.JLabel AirlinerPhoneNumberLabel;
    private javax.swing.JTextField ArrivalTextField;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField DateTextField;
    private javax.swing.JTextField DepartureTextField;
    private javax.swing.JTextField FlightNumberTextField;
    private javax.swing.JTextField TakeoftimeTextField;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox seat;
    // End of variables declaration//GEN-END:variables
}
